version: "3.3"
services:
  angular:
    container_name: angularApp
    build: ./front/
    ports:
      - 4200:4200
    networks:
      - aos
  nodejs:
    container_name: nodeApp
    build: ./back/
    ports:
      - 3000:3000
    networks:
      - aos

networks:
    aos: