import { Document } from 'mongoose';

export interface IUserRightsModel extends Document {
  _id: String;
  UTILITAIRE: {
    UTILITAIRE_ACCESSADMIN_RIGHTS: Boolean,
    UTILITAIRE_UPDATE_USER_ROLE: Boolean,
    UTILITAIRE_UPDATE_USER_RIGHT: Boolean,
    UTILITAIRE_CREATE_USER: Boolean,
    UTILITAIRE_CONSULTATION_MESSAGE: Boolean
  },
  FORUM: {
    FORUM_ACCESSADMIN_RIGHTS: Boolean,
    FORUM_CREATE_SECTION: Boolean,
    FORUM_DELETE_SECTION: Boolean,
    FORUM_CREATE_TOPIC: Boolean,
    FORUM_DELETE_TOPIC: Boolean,
    FORUM_CREATE_MESSAGE: Boolean,
    FORUM_MODERATE_MESSAGE: Boolean
  },
  CHALLENGE: {
    CHALLENGE_ACCESSADMIN_RIGHTS: Boolean,
    CHALLENGE_CREATE: Boolean,
    CHALLENGE_UPDATE: Boolean,
    CHALLENGE_PARTICIPATION: Boolean,
    CHALLENGE_MODERATE_PARTICIPATION: Boolean,
    CHALLENGE_MODERATE_MESSAGE: Boolean
  },
  HONORED_BEATMAKER: {
    HONORED_BEATMAKER_ACCESSADMIN_RIGHTS: Boolean,
    HONORED_BEATMAKER_UPDATE_CURRENT: Boolean,
    HONORED_BEATMAKER_UPDATE_CONTENT: Boolean
  }
}

export function initRights(_id: String): IUserRightsModel {
  return {
    _id: _id,
    UTILITAIRE: {
      UTILITAIRE_ACCESSADMIN_RIGHTS: false,
      UTILITAIRE_UPDATE_USER_ROLE: false,
      UTILITAIRE_UPDATE_USER_RIGHT: false,
      UTILITAIRE_CREATE_USER: false,
      UTILITAIRE_CONSULTATION_MESSAGE: false
    },
    FORUM: {
      FORUM_ACCESSADMIN_RIGHTS: false,
      FORUM_CREATE_SECTION: false,
      FORUM_DELETE_SECTION: false,
      FORUM_CREATE_TOPIC: true,
      FORUM_DELETE_TOPIC: false,
      FORUM_CREATE_MESSAGE: true,
      FORUM_MODERATE_MESSAGE: false
    },
    CHALLENGE: {
      CHALLENGE_ACCESSADMIN_RIGHTS: false,
      CHALLENGE_CREATE: false,
      CHALLENGE_UPDATE: false,
      CHALLENGE_PARTICIPATION: true,
      CHALLENGE_MODERATE_PARTICIPATION: false,
      CHALLENGE_MODERATE_MESSAGE: false
    },
    HONORED_BEATMAKER: {
      HONORED_BEATMAKER_ACCESSADMIN_RIGHTS: false,
      HONORED_BEATMAKER_UPDATE_CURRENT: false,
      HONORED_BEATMAKER_UPDATE_CONTENT: false
    }
  }
}